### ISSUE TITLE
¿Cómo se diseña una app?

### ISSUE THREAD

**Issue by slopma** [Ang3l1485/Seprub#41]
**Espacio para definir el proceso de diseño de interfaz en aplicación**

_Entregar antes del 04/09_

**Comment by Valenciavm** [comment]
Herramienta

Android Studio:

https://developer.android.com/studio?gclid=Cj0KCQjwusunBhCYARIsAFBsUP-atF15h8QlYc2Yc29rakwRzqAFQrKu_aoKnv6KAgQswxtOhlAfo1UaAgYFEALw_wcB&gclsrc=aw.ds
