### ISSUE TITLE
Sketch #1

### ISSUE THREAD

**Issue by slopma** [Ang3l1485/Seprub#43]
**Espacio para entrega del sketch #1 de diseño interno y externo**

_Entregar antes del 04/09_

**Comment by Valenciavm** [comment]
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/dd6635c9-870d-4464-af5a-63dc6fc6d024)
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/291321c9-202b-43d9-b6a8-610a18097708)
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/b9e2d34f-6fb1-451b-ad49-45d18b65e67c)
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/bef1d5bc-3129-4cd6-b63e-840b093f03fe)
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/d24dcd2d-a0cd-486b-b744-d0ac59d8ee80)

**Comment by Valenciavm** [comment]
![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/baba123c-7e69-44e1-a1ba-f1760fa8a287)

![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/5f91d337-2e55-4fc5-9afe-039f5da6b437)

![Image](https://github.com/Ang3l1485/Seprub/assets/141790853/d618017c-0cfd-42da-bd6f-6cc6242a79e5)
